// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.573
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description~CCC
 Language Utility
//

/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="RSSFeedSoap",~CCC
Namespace="http://tempuri.org/"),
System.Diagnostics.DebuggerStepThroughAttribute(),
System.ComponentModel.DesignerCategoryAttribute("code")]
public class RSSFeed: System.Web.Services.Protocols.SoapHttpClientProtocol {

    public RSSFeed () {
        this.Url = "http://localhost:8080/webservice.asmx";
    }

    [System.Web.Services.Protocols.SoapDocumentMethodAttribute(~CCC
"http://tempuri.org/GetFeed",RequestNamespace="http://tempuri.org/",~CCC
ResponseNamespace="http://tempuri.org/",ParameterStyle=System.~CCC
Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=~CCC
System.Web.Services.Description.SoapBindingUse.Literal)]
    public string GetFeed(string FeedURL) {
        object[] results = this.Invoke("GetFeed", new object[] {
            FeedURL});
        return ((string)(results[0]));
    }

    public System.IAsyncResult BeginGetFeed(string FeedURL,~CCC
 System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetFeed", new object[] {
            FeedURL}, callback, asyncState);
    }

    public string EndGetFeed(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
}
