DROP DATABASE IF EXISTS rssaggregator;

CREATE DATABASE rssaggregator;

USE rssaggregator;

CREATE TABLE feed (
  FeedID MEDIUMINT NOT NULL AUTO_INCREMENT,
  FeedURL VARCHAR(255) NOT NULL,
  FeedName VARCHAR(128) NOT NULL,
  PRIMARY KEY(FeedID));


CREATE TABLE channel (
  ChannelID MEDIUMINT NOT NULL AUTO_INCREMENT,
  FeedID MEDIUMINT REFERENCES feed(FeedID),
  Title VARCHAR(128) NOT NULL,
  Link VARCHAR(255) NOT NULL,
  Description VARCHAR(128) NOT NULL,
  Language VARCHAR(6) NULL,
  PublishedDate DATE NULL,
  Category VARCHAR(32) NULL,
  PRIMARY KEY(ChannelID));

CREATE TABLE channelitems (
  ItemID MEDIUMINT NOT NULL AUTO_INCREMENT,
  ChannelID MEDIUMINT REFERENCES channel(ChannelID),
  Title VARCHAR(255) NOT NULL,
  Link VARCHAR(128) NOT NULL,
  Description VARCHAR(128) NOT NULL,
  Author VARCHAR(32) NULL,
  PublishedDate DATE NULL,
  PRIMARY KEY(ItemID));
